[package]
name = "treereduce-yabo"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
treereduce = { version="0.3.0", features=["cli"] }
tree-sitter-yabo = { path = "../tree-sitter-yabo" }
anyhow = "1"