name:                ybq
version:             0.1.0.0
github:              "8051enthusiast/yabo"
license:             BSD-3-Clause
author:              "8051enthusiast"
maintainer:          "8051enthusiast@protonmail.com"
copyright:           "Copyright 2024 8051enthusiast"
language:            "GHC2021"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/8051enthusiast/ybq#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- mtl
- transformers
- unix
- parsec
- mmap >= 0.5.9
- file-embed >= 0.0.16

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources: src/yabo-bindings.c

executables:
  ybq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ybq

tests:
  ybq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ybq
