[package]
name = "yaboc-target"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
yaboc-base = { path = "../yaboc-base" }
paste = "1.0.15"
tempfile = "3.13.0"
