[package]
name = "yaboc-len"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
rand = "0.8.5"
regex-syntax = "0.8.5"
smallvec = { workspace = true }
yaboc-req = { path = "../yaboc-req" }
